# Django settings for omm project.
from lingcod.common.default_settings import *

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'watersheds',
        'USER': 'postgres',
     }
}

GEOMETRY_DB_SRID = 99999

TIME_ZONE = 'America/Vancouver'
LANGUAGE_CODE = 'en-us'
SITE_ID = 1
USE_I18N = True

#SECRET_KEY = 'keep_the_one_autogenerated_by_django-admin'

ROOT_URLCONF = 'wp.urls'

TEMPLATE_DIRS = ( os.path.realpath(os.path.join(os.path.dirname(__file__), 'templates').replace('\\','/')), )

INSTALLED_APPS += ( 'arp', 
                    'lingcod.analysistools',
                  )
# The following is used to assign a name to the default folder under My Shapes 
KML_UNATTACHED_NAME = 'Areas of Inquiry'

#These two variables are used to determine the extent of the zoomed in image in lingcod.staticmap
#If one or both are set to None or deleted entirely than zoom will default to a dynamic zoom generator
STATICMAP_WIDTH_BUFFER = .04
STATICMAP_HEIGHT_BUFFER = .12
#These two variables are used in conjunction with the above two variables to create a map extent indicator
#which is basically a rectangle on another map that outlines the extent of the zoomed in area (see oregon.xml)
STATICMAP_OUTLINE_X_OFFSET = .07
STATICMAP_OUTLINE_Y_OFFSET = .14

from settings_local import *
